export const data = [
  {
    id: 1,
    name: 'Trường Đại học Khoa học Tự Nhiên TPHCM',
    shortDesc: 'Đào tạo bài bản, những kỹ sư tương lai công nghệ',
    major: ['Công nghệ thông tin', 'Thiết kế đồ họa', 'Kinh doanh quốc tế'],
    description:
      'Tạo một môi trường năng động tích cực cho sinh viên. Nâng cao kỹ năng mềm',
    grade: 22,
    image:
      'https://media.publit.io/file/truong-dai-hoc-fpt-tp-hcm-1.jpg?fbclid=IwAR16cWCEg-Ef7UvVg418IR3DFd7ZiFyt4-f-IgTdpJWZ8p3X0YkWwovf2Ic',
    majorInfo: [
      {name: 'Ngành kỹ thuật phần mềm', grade: 22},
      {name: 'Ngành Kinh doanh quốc tế', grade: 20},
      {name: 'Ngành Kinh tế học', grade: 16},
      {name: 'Ngôn ngữ Anh', grade: 18},
      {name: 'Ngôn ngữ Nhật', grade: 18},
      {name: 'Ngành thiết kế đồ họa', grade: 21},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
    ],
  },
  {
    id: 2,
    name: 'Trường Đại học Bách Khoa TPHCM',
    shortDesc: 'Đào tạo bài bản, những kỹ sư tương lai công nghệ',
    major: ['Công nghệ thông tin', 'Thiết kế đồ họa', 'Kinh doanh quốc tế'],
    description:
      'Tạo một môi trường năng động tích cực cho sinh viên. Nâng cao kỹ năng mềm',
    grade: 18,
    image:
      'https://media.publit.io/file/truong-dai-hoc-fpt-tp-hcm-1.jpg?fbclid=IwAR16cWCEg-Ef7UvVg418IR3DFd7ZiFyt4-f-IgTdpJWZ8p3X0YkWwovf2Ic',
    majorInfo: [
      {name: 'Ngành kỹ thuật phần mềm', grade: 22},
      {name: 'Ngành Kinh doanh quốc tế', grade: 20},
      {name: 'Ngành Kinh tế học', grade: 16},
      {name: 'Ngôn ngữ Anh', grade: 18},
      {name: 'Ngôn ngữ Nhật', grade: 18},
      {name: 'Ngành thiết kế đồ họa', grade: 21},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
    ],
  },
  {
    id: 3,
    name: 'Trường Đại học Khoa học Xã hội và Nhân văn TPCHM',
    shortDesc:
      'Đào tạo bài bản, những công dân gương mãu, tài tình cho đất nước',
    major: ['Công nghệ thông tin', 'Thiết kế đồ họa', 'Kinh doanh quốc tế'],
    description:
      'Tạo một môi trường năng động tích cực cho sinh viên. Nâng cao kỹ năng mềm',
    grade: 17,
    image:
      'https://media.publit.io/file/truong-dai-hoc-fpt-tp-hcm-1.jpg?fbclid=IwAR16cWCEg-Ef7UvVg418IR3DFd7ZiFyt4-f-IgTdpJWZ8p3X0YkWwovf2Ic',
    majorInfo: [
      {name: 'Ngành kỹ thuật phần mềm', grade: 22},
      {name: 'Ngành Kinh doanh quốc tế', grade: 20},
      {name: 'Ngành Kinh tế học', grade: 16},
      {name: 'Ngôn ngữ Anh', grade: 18},
      {name: 'Ngôn ngữ Nhật', grade: 18},
      {name: 'Ngành thiết kế đồ họa', grade: 21},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
    ],
  },
  {
    id: 4,
    name: 'Trường Đại học FPT TPHCM',
    shortDesc: 'Đào tạo bài bản, những kỹ sư tương lai công nghệ',
    major: ['Công nghệ thông tin', 'Thiết kế đồ họa', 'Kinh doanh quốc tế'],
    description:
      'Tạo một môi trường năng động tích cực cho sinh viên. Nâng cao kỹ năng mềm',
    grade: 21,
    image:
      'https://media.publit.io/file/truong-dai-hoc-fpt-tp-hcm-1.jpg?fbclid=IwAR16cWCEg-Ef7UvVg418IR3DFd7ZiFyt4-f-IgTdpJWZ8p3X0YkWwovf2Ic',
    majorInfo: [
      {name: 'Ngành kỹ thuật phần mềm', grade: 22},
      {name: 'Ngành Kinh doanh quốc tế', grade: 20},
      {name: 'Ngành Kinh tế học', grade: 16},
      {name: 'Ngôn ngữ Anh', grade: 18},
      {name: 'Ngôn ngữ Nhật', grade: 18},
      {name: 'Ngành thiết kế đồ họa', grade: 21},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
    ],
  },
  {
    id: 5,
    name: 'Trường Đại học Sư phạm kỹ thuật TPHCM',
    shortDesc: 'Đào tạo bài bản, những kỹ sư tương lai công nghệ',
    major: ['Công nghệ thông tin', 'Thiết kế đồ họa', 'Kinh doanh quốc tế'],
    description:
      'Tạo một môi trường năng động tích cực cho sinh viên. Nâng cao kỹ năng mềm',
    grade: 22,
    image:
      'https://media.publit.io/file/truong-dai-hoc-fpt-tp-hcm-1.jpg?fbclid=IwAR16cWCEg-Ef7UvVg418IR3DFd7ZiFyt4-f-IgTdpJWZ8p3X0YkWwovf2Ic',
    majorInfo: [
      {name: 'Ngành kỹ thuật phần mềm', grade: 22},
      {name: 'Ngành Kinh doanh quốc tế', grade: 20},
      {name: 'Ngành Kinh tế học', grade: 16},
      {name: 'Ngôn ngữ Anh', grade: 18},
      {name: 'Ngôn ngữ Nhật', grade: 18},
      {name: 'Ngành thiết kế đồ họa', grade: 21},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
    ],
  },
  {
    id: 6,
    name: 'Trường Đại học Công nghệ thông tin TPHCM',
    shortDesc: 'Đào tạo bài bản, những kỹ sư tương lai công nghệ',
    major: ['Công nghệ thông tin', 'Thiết kế đồ họa', 'Kinh doanh quốc tế'],
    description:
      'Tạo một môi trường năng động tích cực cho sinh viên. Nâng cao kỹ năng mềm',
    grade: 21,
    image:
      'https://media.publit.io/file/truong-dai-hoc-fpt-tp-hcm-1.jpg?fbclid=IwAR16cWCEg-Ef7UvVg418IR3DFd7ZiFyt4-f-IgTdpJWZ8p3X0YkWwovf2Ic',
    majorInfo: [
      {name: 'Ngành kỹ thuật phần mềm', grade: 22},
      {name: 'Ngành Kinh doanh quốc tế', grade: 20},
      {name: 'Ngành Kinh tế học', grade: 16},
      {name: 'Ngôn ngữ Anh', grade: 18},
      {name: 'Ngôn ngữ Nhật', grade: 18},
      {name: 'Ngành thiết kế đồ họa', grade: 21},
      {name: 'Ngành Quản trị kinh doanh', grade: 15},
    ],
  },
];
